import {test} from 'node:test';
import assert from 'node:assert/strict';
import {preset,switchUnit,blockGap,buildCSS,renderMarkdown,normalize,sample} from '../dist/model.js';
test('px and multiplier round trip preserves equivalent line height',()=>{const style=preset().body;const times=switchUnit(style,'multiplier');assert.equal(times.line,1.7);assert.equal(switchUnit(times,'px').line,25.5);assert.equal(switchUnit({...times,size:20},'px').line,34);});
test('blocks use max not sum; divider and title precedence',()=>{const c=preset();c.body.after=16;c.quote.before=24;assert.equal(blockGap(c,'body','quote'),24);c.hr.before=32;c.hr.after=20;assert.equal(blockGap(c,'body','hr'),32);assert.equal(blockGap(c,'hr','h2'),20);c.tightTitles=true;assert.equal(blockGap(c,'h2','h3'),8);assert.equal(blockGap(c,'body','h3'),16);});
test('independent scene and table typography are emitted',()=>{const c=preset('app');c.thead.size=20;c.table.size=13;c.table.unit='multiplier';c.table.line=1.8;const css=buildCSS(c);assert.match(css,/\.answer th\{[^}]*font-size:20px/);assert.match(css,/\.answer td\{[^}]*line-height:1.8;/);assert.equal(preset('web').body.size,15);assert.equal(preset('app').body.size,17);});
test('GFM sample supports headings, nested lists, tables, code and rule',()=>{const html=renderMarkdown(sample);for(const tag of ['h1','h2','h3','h4','h5','h6','ol','ul','blockquote','table','pre','hr'])assert.match(html,new RegExp('<'+tag+'[ >]'));assert.match(html,/class="md-table"/);assert.match(html,/type="checkbox"/);});
test('raw HTML and unsafe links cannot execute; images do not load',()=>{const html=renderMarkdown('<img src=x onerror=alert(1)>\n\n[x](javascript:alert)\n\n![x](https://example.com/a.png)\n\n[x](https://example.com)');assert.doesNotMatch(html,/<img|href="javascript:|onerror="/);assert.match(html,/&lt;img/);assert.match(html,/rel="noopener noreferrer"/);});
test('stored preferences are clamped and cannot inject CSS',()=>{const c=normalize({body:{size:999,color:'red;}body{display:none',font:'evil',line:-1,unit:'px'},width:4},'web');assert.equal(c.body.size,64);assert.equal(c.body.color,'#242a33');assert.equal(c.body.line,10);assert.equal(c.width,280);});
